apiVersion: v1
name: nats-streaming-operator
version: 1.0.1
appVersion: 0.2.3
description: Operator for managing NATS Streaming clusters running on Kubernetes.
keywords:
- nats
- streaming
- delivery
- ratelimit
- replay
- restart
home: https://github.com/nats-io/nats-streaming-operator
sources:
- https://github.com/nats-io/nats-streaming-operator
maintainers:
- name: starefossen
  email: hans@starefossen.com
icon: https://bitnami.com/assets/stacks/nats/img/nats-stack-110x117.png
